### ISSUE TITLE
Joomla KM for SMD

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/ITIL-CMDB#1]
STEPS FOR COPYING NEW INSTANCE OF JOOMLA KM  FOR SMD
===============

1.	Empty Database creation as joomlasmd.
2.	Import joomlakm2 database into joomlasmd.
3.	Copy /opt/lampp/htdocs/joomlakm /opt/lampp/htdocs/joomlasmd
4.	Edit /opt/lampp/htdocs/joomlasmd/installation/configuration.php
                public $db = 'joomlasmd';
                public $log_path = '/opt/lampp/htdocs/joomlasmd/logs';
                public $tmp_path = '/opt/lampp/htdocs/joomlasmd/tmp';

5.	Copy joomlakm2 folder in linux as joomlasmd
6.	Change path of all location for joomlasmd database to joomlasmd folder.

**JoomlaKM for SMD created**

http://192.9.200.172:8080/joomlasmd/

**Comment by hariharan-isgec** [comment]
@isgecharish Configure Login and Articles as per SMD's requirement
@dhirendra-isgec @bhupender-isgec FYI for backup

**Comment by bhupender-isgec** [comment]
Noted sir will add into backup list.

 

Thanks

Bhupender K Kashyap
