### ISSUE TITLE
Installation of Revit structure Application in 12 Users (Biler-Mechanical)

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-CMDB#10]
Request you to install the Revit Structure (latest version available 2020) software for the following members.

Name | Emp.Code | Mail ID.
-- | -- | --
Pramod Kumar | 881 | pramodkumar@isgec.co.in
Brijesh Kumar | 2903 | brijesh.kumar@isgec.co.in
A. Mohamed Ibrahim | 2626 | a.ibrahim@isgec.co.in
Jitender Prasad Gupta | 1293 | jitendragupta@isgec.co.in
Dinesh Kumar | 2999 | dinesh.kumar4@isgec.co.in
Pardeep Kumar | 3656 | pradeep.kumar@isgec.co.in
Bhumesh | 3662 | bhumesh.kumar@isgec.co.in
Prakash Shankar Borate | 3611 | prakash.borate@isgec.co.in
Rahul Saini | 10187 | rahul.saini@isgec.co.in
Neeraj Kumar |   | nkumar@isgec.co.in
Manjit solanki |   | manjitsolanki@isgec.co.in
Santhose Ram |   | santoshram@isgec.co.in

@Isgec/dc-infra-team , I am working on this task with Helpdesk Team.

**Comment by msrawat-isgec** [comment]
Dear Team,

 

Revit 2020 access permissions are given to all below mentioned  user's
account. Please install Revit 2020 in all below mentioned user's machines.

 

Revit 2020 is downloaded and keep it in below mentioned path. Please install
accordingly.

 

\\192.168.25.75\AUTODESK_2020\Revit_2020
<file:///\\192.168.25.75\AUTODESK_2020\Revit_2020> 

 

 

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: helpdesk.noida63-request@isgec.co.in
[mailto:helpdesk.noida63-request@isgec.co.in] On Behalf Of ESG Pragasam
Sent: 15 January 2021 15:12
To: 'Support Team 63'; 'Praveen Kumar'
Cc: 'K Satheesh Kumar'; 'R. Arunkumar'; 'Harish Kaushik'; 'Rajesh kumar
Vashist'
Subject: RE: Installation of Revit structure- 

 

Please do the needed. 

 

I suggest installing AEC 2020 version as we will be moving into this soon.
Leave the existing AUTOCAD 2018 for 3 months . Once we migrate , we will
remove .

 

Thanks

ESG Pragasam

ESC-Mechanical

Ph+919818995687

 

From: R. Arunkumar <r.arunkumar@isgec.co.in> 
Sent: 15 January 2021 15:07
To: 'Support Team 63' <helpdesk.noida63@isgec.co.in>; 'Praveen Kumar'
<praveen1.kumar@isgec.co.in>
Cc: Esg Pragasam <esgpragasam@isgec.co.in>; 'K Satheesh Kumar'
<k.satheeshkumar@isgec.co.in>
Subject: RE: Installation of Revit structure- 

 

Dear Sir,

 

Request to install the Revit for following user also.

 

1.	Neeraj Kumar
2.	Manjit solanki
3.	Santhose Ram

 

Regards

 

R.Arunkumar

Extn: 1540

9910991179

 

From: Satheesh Kumar [mailto:k.satheeshkumar@isgec.co.in] 
Sent: 15 January 2021 14:45
To: r.arunkumar@isgec.co.in
Subject: FW: Installation of Revit structure- 

 

 

From: Satheesh Kumar <k.satheeshkumar@isgec.co.in> 
Sent: 15 January 2021 14:43
To: Helpdesk - Noida63 <helpdesk.noida63@isgec.co.in>; praveen kumar
<praveen.kumar55@isgec.co.in>
Cc: 'ESG Pragasam' <esgpragasam@isgec.co.in>; 'nbala' <nbala@isgec.co.in>;
'gaurav.kumar@isgec.co.in'; 'dinesh.kumar4@isgec.co.in';
'pramodkumar@isgec.co.in'; 'jitendra.gupta@isgec.co.in';
'pardeep.kumar@isgec.co.in'; 'Rahul Sani' <rahul.saini@isgec.co.in>;
'bhumesh.kumar@isgec.co.in'; 'Brijesh Kumar' <brijesh.kumar@isgec.co.in>;
'a.ibrahim@isgec.co.in'
Subject: Installation of Revit structure- 

 

Dear Sir,

 

Request you to install the Revit Structure (latest version available)
software for the following members.

 


Name

Emp.Code

Mail ID.


Pramod Kumar    

0881

 <mailto:pramodkumar@isgec.co.in> pramodkumar@isgec.co.in


Brijesh Kumar

2903

 <mailto:brijesh.kumar@isgec.co.in> brijesh.kumar@isgec.co.in


A. Mohamed Ibrahim

2626

 <mailto:a.ibrahim@isgec.co.in> a.ibrahim@isgec.co.in


Jitender Prasad Gupta

1293

 <mailto:jitendragupta@isgec.co.in> jitendragupta@isgec.co.in


Dinesh Kumar

2999

 <mailto:dinesh.kumar4@isgec.co.in> dinesh.kumar4@isgec.co.in


Pardeep Kumar

3656

pradeep.kumar@isgec.co.in


Bhumesh

3662

bhumesh.kumar@isgec.co.in


Prakash Shankar Borate

3611

prakash.borate@isgec.co.in


Rahul Saini

10187

rahul.saini@isgec.co.in

	
 

 

Dear JDP Sir,

 

Request your approval.

 

Thanks & Regards,

 

K.Satheesh Kumar

Extn.:1694

Mobile: 9599223213
