### ISSUE TITLE
AccelPro VPN for two months till 25-03-2021, Rajkumar(3454)- NTPC Barh site

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-CMDB#11]
From: helpdesk.noida63-request@isgec.co.in [mailto:helpdesk.noida63-request@isgec.co.in] On Behalf Of Rajkumar
Sent: 22 January 2021 09:45
To: helpdesk.noida63@isgec.co.in
Cc: harish.bisht@isgec.co.in; praveen.singh1@isgec.co.in
Subject: Approval for Laptop for NTPC Barh site

Dear sir,
With reference to trailing mail ,As discussed with Mr arun kindly provide following software in the laptop being issued:

1.EXCEL
2.MS Office
3.Any desk
4.Baan
5.Vault viewer
6.Accel pro for long period 

Thanks & Regards

Rajkumar s mune
Projects FGD 

 

A-5, Sec-63, Noida(U.P.)
Mob No: 7303244922
Web site:www.isgec.com
 

From: vinay.sharma@isgec.co.in [mailto:vinay.sharma@isgec.co.in] 
Sent: 21 January 2021 14:10
To: Suman Jain
Cc: vinay.sharma@isgec.co.in; Harish Bisht; Abhay Singh
Subject: Re: RE: Approval for Laptop for NTPC Barh site

Noted sir,
We will issue a good working laptop as per requirement.
Regards
Vinay
--
Sent from myMail for Android
Thursday, 21 January 2021, 01:02PM +05:30 from Suman Jain suman@isgec.co.in:
Approved.
 
 
Suman Jain
 
Group Head
- Utility Boilers 
-New Technology Development
- Air Pollution Control Equipment
 
A-5, Sector 63, Noida – 201 301 U.P., India
Mobile: +91-8800500241
Website: www.isgec.com
Follow us on:
Facebook | Youtube | Instagram | LinkedIn | Twitter
 
From: Abhay Singh <abhay.singh@isgec.co.in> 
Sent: Wednesday, January 20, 2021 6:03 PM
To: suman@isgec.co.in
Cc: vinay.sharma@isgec.co.in; 'Harish Bisht' <harish.bisht@isgec.co.in>
Subject: RE: Approval for Laptop for NTPC Barh site
 
Dear Sir,
 
We require this laptop for tentative period of 2 month.
 
This will be issued by our IT team.
 
Kindly accord your approval.
 
Thanks & Regards
 
Abhay Pratap Singh
Project Manager
 
A-5, Sector 63, Noida – 201301 
Landline: +91 120 4085945
Mobile: +91 9899144815
Email: abhay.singh@isgec.co.in
Website: www.isgec.com
 
From: Harish Bisht [mailto:harish.bisht@isgec.co.in] 
Sent: Wednesday, January 20, 2021 5:59 PM
To: suman@isgec.co.in
Cc: abhay.singh@isgec.co.in; vinay.sharma@isgec.co.in
Subject: Approval for Laptop for NTPC Barh site
 
Note
 
 
IT Department                                                  thru                                                       SJ
 
 
Dear Sir,
 
This is with reference to our BARH NTPC Project, we are planning a visit to NTPC Barh site on 26-01-2021 to start measurement and reverse engineering work for “Duct & Structure” along with engineering team.
 
Laptop is required at site for daily communication between ISGEC and NTPC and other works.
 
Kindly accord your approval for same.
 
Submitted for your approval.
 
Regards,
 
Harish Bisht

@Isgec/dc-infra-team , Myself Praveen is working for creation AccelPro VPN with required permissions through VPN.

**Comment by vinay-isgec** [comment]
Regards

Vinay
