### ISSUE TITLE
Approval for creating login ID and access to AutoCAD and Cadison software(s) for Mrs. Rohini Kiran Fale 

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-CMDB#14]
We have taken Mrs. Rohini Kiran Fale on Project contract basis at our Pune Office. She was an erstwhile employee of ISGEC with Employee No. 2869. This step was necessary to expedite the extraction and correction of isometric drawings for SSM Distillery project. Request you to approve for creating login ID and access to AutoCAD and Cadison software(s) for Mrs. Rohini Kiran Fale.
 
Regards,
CH S N Sreenivasa
@Isgec/dc-infra-team , Myself Praveen and Mr. Bhupendra will work first then we will inform to Helpdesk team.

**Comment by praveen-isgec** [comment]
Hi Team,

 

We required official   mail id for creating Autodesk Account. Please create mail account accordingly.

 

 

From: Vinay Sharma [mailto:vinay.sharma@isgec.co.in] 

Sent: 28 January 2021 11:08

To: praveen1.kumar@isgec.co.in; helpdesk.pune@isgec.co.in

Subject: FW: Approval for creating login ID and access to AutoCAD and Cadison software(s) for Mrs. Rohini Kiran Fale 

 

Dear Praveen, 

 

Please give autocad and cadision software access to the user as per KV approval in the given mail.

 

@ madan  please update me once its done from your side 

 

Regards

Vinay 

 

From: K Viswanathan [mailto:k.viswanathan@isgecsfw.com] 

Sent: 28 January 2021 10:57

To: CH S N Sreenivasa; ''k. viswananthan''

Cc: jkkharbanda@isgec.co.in; smahuli@isgec.co.in; 'hariharan.m'; ''vinay sharma''

Subject: Re: Approval for creating login ID and access to AutoCAD and Cadison software(s) for Mrs. Rohini Kiran Fale 

 

Approved.

 

Regards,

KV

 

Get Outlook for iOS

________________________________________

From: CH S N Sreenivasa <chsn.sreenivasa@isgec.co.in>

Sent: Thursday, January 28, 2021 10:41:31 AM

To: ''k. viswananthan'' <kviswanathan@isgec.co.in>

Cc: jkkharbanda@isgec.co.in <jkkharbanda@isgec.co.in>; smahuli@isgec.co.in <smahuli@isgec.co.in>; 'hariharan.m' <hariharan.m@isgec.co.in>; ''vinay sharma'' <vinay.sharma@isgec.co.in>

Subject: Approval for creating login ID and access to AutoCAD and Cadison software(s) for Mrs. Rohini Kiran Fale 

 

Dear KV Sir,

We have taken Mrs. Rohini Kiran Fale on Project contract basis at our Pune Office. She was an erstwhile employee of ISGEC with Employee No. 2869. This step was necessary to expedite the extraction and correction of isometric drawings for SSM Distillery project. Request you to approve for creating login ID and access to AutoCAD and Cadison software(s) for Mrs. Rohini Kiran Fale.

Regards,

CH S N Sreenivasa

Landline (direct) : 01204085087

Landline: 01204085001 Extn 5087

Mobile Phone 7619613170

 

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

**Comment by bhupender-isgec** [comment]
Dear,

 

Against what Employee ID this email needs to be created.

 

Thanks

Bhupender K Kashyap

**Comment by bhupender-isgec** [comment]
As discussed I have created email id as smdcad01@isgec.co.in <mailto:smdcad01@isgec.co.in>  on 215

 

Thanks

Bhupender K Kashyap

 

 

From: Bhupender K Kashyap <bhupender.kashyap@isgec.co.in> 
Sent: 28 January 2021 18:14
To: 'Isgec/ITIL-CMDB' <reply@reply.github.com>; 'Isgec/ITIL-CMDB' <ITIL-CMDB@noreply.github.com>
Cc: 'Bhupender K Kashyap' <bhupenderkashyap@isgec.co.in>; 'Team mention' <team_mention@noreply.github.com>
Subject: RE: [Isgec/ITIL-CMDB] Approval for creating login ID and access to AutoCAD and Cadison software(s) for Mrs. Rohini Kiran Fale (#14)

 

Dear,

 

Against what Employee ID this email needs to be created.

 

Thanks

Bhupender K Kashyap

**Comment by praveen-isgec** [comment]
Dear Madan,

 

Domain account is created for mentioned third party users]. Details as follows.

 

User Name:                        smdcad01

Password:                           Welcome@123

Domain:                               isgecnet.com

Computer Name:             smdcad01

 

Autodesk Account Details as follows.

 

smdcad01@isgec.co.in  (Please install Autocad 2020 in user’s machine)

 

 

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785
