### ISSUE TITLE
Autocad 2020 with tool set installation request

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-CMDB#17]
Kindly install the AutoCAD 2020 with following toolset for below person
 
Tool Set: 
 
01.	ARCHITECTURE TOOLSET
02.	MECHANICAL TOOLSET
03.	MEP TOOLSET
04.	PLANT 3D TOOLSET
 
Employee detail:
 
1.	R.Arunkumar (Emply  Code : 1974)
2.	R.Saravanan (Emply Code: 3877)
 
Regards
 R.Arunkumar,
Boiler-Mechanical
I checked on Autodesk console and foud both mentioned users having ACE licenses , Now we have to give additional AUTOCAD license because all above mentioned componets are part od AUTOCAD instead of AEC.
@Isgec/dc-infra-team  , Myself Praveen Kumar is working for the same.

**Comment by msrawat-isgec** [comment]
Dear Team,

 

All mentioned applications are the part of AUTOCAD but both mentioned users
are having AEC license. Now I added Autocad license for bot users besides
AEC.

 

I download all mentioned application with required updates. Path details as
follows.

 

\\192.168.25.75\AUTODESK_2020 <file:///\\192.168.25.75\AUTODESK_2020> 

 

Please install only below mentioned applications with given updates.

*	AutoCAD Architecture -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_Architecture_2020_0_2_Update_html> 2020.0.2 (Includes
2020.0.1)
*	AutoCAD MEP -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_MEP_2020_0_2_Update_html> 2020.0.2 (Includes 2020.0.1)
*	AutoCAD Mechanical -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_Mechanical_2020_0_1_Update_html> 2020.0.1
*	AutoCAD Plant 3D -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_Plant3D_2020_1_Update_html> 2020.1 (Includes 2020.0.1)

 

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: helpdesk.noida63-request@isgec.co.in
[mailto:helpdesk.noida63-request@isgec.co.in] On Behalf Of Harish Kaushik
Sent: 29 January 2021 14:08
To: 'Praveen Kumar'; 'Support Team 63'
Cc: 'R. Arunkumar'; 'Esg Pragasam'
Subject: RE: Autocad 2020 with tool set installation request

 

Download link.

 

https://manage.autodesk.com/cep/?
<https://manage.autodesk.com/cep/?&_ga=2.113159620.1160711967.1611908667-191
4529307.1611908667#products-services/updates>
&_ga=2.113159620.1160711967.1611908667-1914529307.1611908667#products-servic
es/updates

 

From: Harish Kaushik <harish.kaushik@isgec.co.in> 
Sent: 29 January 2021 14:04
To: 'Praveen Kumar' <praveen1.kumar@isgec.co.in>; 'Support Team 63'
<helpdesk.noida63@isgec.co.in>
Cc: 'R. Arunkumar' <r.arunkumar@isgec.co.in>; 'Esg Pragasam'
<esgpragasam@isgec.co.in>
Subject: RE: Autocad 2020 with tool set installation request

 

Dear Praveen,

 

As discussed, please install following products with mentioned update
version to get benefit of Specialized Toolset of Autodesk AUTOCAD Package.

*	AutoCAD Architecture -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_Architecture_2020_0_2_Update_html> 2020.0.2 (Includes
2020.0.1)
*	AutoCAD MEP -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_MEP_2020_0_2_Update_html> 2020.0.2 (Includes 2020.0.1)
*	AutoCAD Mechanical -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_Mechanical_2020_0_1_Update_html> 2020.0.1
*	AutoCAD Electrical -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_Electrical_2020_0_1_Update_html> 2020.0.1
*	AutoCAD Plant 3D -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_Plant3D_2020_1_Update_html> 2020.1 (Includes 2020.0.1)
*	AutoCAD Map 3D -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_M3D_2020_0_1_Update_html> 2020.0.1

 

 

Please ask in case of any doubt.

 

 

Thanks & Regards,

Harish Kaushik

From: R. Arunkumar <r.arunkumar@isgec.co.in> 
Sent: 29 January 2021 10:57
To: 'Praveen Kumar' <praveen1.kumar@isgec.co.in>; 'Support Team 63'
<helpdesk.noida63@isgec.co.in>
Cc: Esg Pragasam <esgpragasam@isgec.co.in>; Harish Kaushik
<harish.kaushik@isgec.co.in>
Subject: Autocad 2020 with tool set installation request

 

Dear Sir,

 

Kindly install the AutoCAD 2020 with following toolset for below person

 

Tool Set: 

 

1.	ARCHITECTURE TOOLSET
2.	MECHANICAL TOOLSET
3.	MEP TOOLSET
4.	PLANT 3D TOOLSET

 

Employee detail:

 

1.	R.Arunkumar (Emply  Code : 1974)
2.	R.Saravanan (Emply Code: 3877)

 

Regards

 
R.Arunkumar,

Boiler-Mechanical

Isgec eSign
A56,Sector-63,Noida-201301 U.P.,India

Tel.:+91-120-408 5500 Ext.1540

Direct: +91-120-458 1540
Mobile : +91-9910991179

Email:r.arunkumar@isgec.co.in

website:www.isgec.com

7 Switch off as you go   |   qRecycle always   |   P Think & Print  - Save
Paper - Save Trees  |  Description: cid:image003.jpg@01CA8223.3FC8A220 Go
Green

Please do not print this email unless it is absolutely necessary. Spread
environmental awareness.

**Comment by msrawat-isgec** [comment]
Dear Praveen, 

 

No need to add AUTOCAD package separately as AEC also includes AUTOCAD.

*Adding will consume both AEC and AUTOCAD package license.

 

Thanks & Regards,

Harish Kaushik

From: Praveen Kumar <praveen1.kumar@isgec.co.in> 
Sent: 03 February 2021 15:51
To: 'Support Team 63' <helpdesk.noida63@isgec.co.in>
Cc: 'R. Arunkumar' <r.arunkumar@isgec.co.in>; 'Esg Pragasam'
<esgpragasam@isgec.co.in>; 'Harish Kaushik' <harish.kaushik@isgec.co.in>;
reply@reply.github.com;
vinay.sharma@isgec.co.in; dhirendra.singh@isgec.co.in
Subject: RE: Autocad 2020 with tool set installation request

 

 

Dear Team,

 

All mentioned applications are the part of AUTOCAD but both mentioned users
are having AEC license. Now I added Autocad license for bot users besides
AEC.

 

I download all mentioned application with required updates. Path details as
follows.

 

\\192.168.25.75\AUTODESK_2020 <file://192.168.25.75/AUTODESK_2020> 

 

Please install only below mentioned applications with given updates.

*	AutoCAD Architecture -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_Architecture_2020_0_2_Update_html> 2020.0.2 (Includes
2020.0.1)
*	AutoCAD MEP -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_MEP_2020_0_2_Update_html> 2020.0.2 (Includes 2020.0.1)
*	AutoCAD Mechanical -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_Mechanical_2020_0_1_Update_html> 2020.0.1
*	AutoCAD Plant 3D -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_Plant3D_2020_1_Update_html> 2020.1 (Includes 2020.0.1)

 

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in <mailto:praveen1.kumar@isgec.co.in> 

website: www.isgec.com <http://www.isgec.com> 

Mobile:  +91 8448595785

 

From: helpdesk.noida63-request@isgec.co.in
<mailto:helpdesk.noida63-request@isgec.co.in>
[mailto:helpdesk.noida63-request@isgec.co.in] On Behalf Of Harish Kaushik
Sent: 29 January 2021 14:08
To: 'Praveen Kumar'; 'Support Team 63'
Cc: 'R. Arunkumar'; 'Esg Pragasam'
Subject: RE: Autocad 2020 with tool set installation request

 

Download link.

 

https://manage.autodesk.com/cep/?
<https://manage.autodesk.com/cep/?&_ga=2.113159620.1160711967.1611908667-191
4529307.1611908667#products-services/updates>
&_ga=2.113159620.1160711967.1611908667-1914529307.1611908667#products-servic
es/updates

 

From: Harish Kaushik <harish.kaushik@isgec.co.in
<mailto:harish.kaushik@isgec.co.in> > 
Sent: 29 January 2021 14:04
To: 'Praveen Kumar' <praveen1.kumar@isgec.co.in
<mailto:praveen1.kumar@isgec.co.in> >; 'Support Team 63'
<helpdesk.noida63@isgec.co.in <mailto:helpdesk.noida63@isgec.co.in> >
Cc: 'R. Arunkumar' <r.arunkumar@isgec.co.in <mailto:r.arunkumar@isgec.co.in>
>; 'Esg Pragasam' <esgpragasam@isgec.co.in <mailto:esgpragasam@isgec.co.in>
>
Subject: RE: Autocad 2020 with tool set installation request

 

Dear Praveen,

 

As discussed, please install following products with mentioned update
version to get benefit of Specialized Toolset of Autodesk AUTOCAD Package.

*	AutoCAD Architecture -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_Architecture_2020_0_2_Update_html> 2020.0.2 (Includes
2020.0.1)
*	AutoCAD MEP -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_MEP_2020_0_2_Update_html> 2020.0.2 (Includes 2020.0.1)
*	AutoCAD Mechanical -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_Mechanical_2020_0_1_Update_html> 2020.0.1
*	AutoCAD Electrical -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_Electrical_2020_0_1_Update_html> 2020.0.1
*	AutoCAD Plant 3D -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_Plant3D_2020_1_Update_html> 2020.1 (Includes 2020.0.1)
*	AutoCAD Map 3D -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_M3D_2020_0_1_Update_html> 2020.0.1

 

 

Please ask in case of any doubt.

 

 

Thanks & Regards,

Harish Kaushik

From: R. Arunkumar <r.arunkumar@isgec.co.in <mailto:r.arunkumar@isgec.co.in>
> 
Sent: 29 January 2021 10:57
To: 'Praveen Kumar' <praveen1.kumar@isgec.co.in
<mailto:praveen1.kumar@isgec.co.in> >; 'Support Team 63'
<helpdesk.noida63@isgec.co.in <mailto:helpdesk.noida63@isgec.co.in> >
Cc: Esg Pragasam <esgpragasam@isgec.co.in <mailto:esgpragasam@isgec.co.in>
>; Harish Kaushik <harish.kaushik@isgec.co.in
<mailto:harish.kaushik@isgec.co.in> >
Subject: Autocad 2020 with tool set installation request

 

Dear Sir,

 

Kindly install the AutoCAD 2020 with following toolset for below person

 

Tool Set: 

 

1.	ARCHITECTURE TOOLSET
2.	MECHANICAL TOOLSET
3.	MEP TOOLSET
4.	PLANT 3D TOOLSET

 

Employee detail:

 

1.	R.Arunkumar (Emply  Code : 1974)
2.	R.Saravanan (Emply Code: 3877)

 

Regards

 
R.Arunkumar,

Boiler-Mechanical


A56,Sector-63,Noida-201301 U.P.,India

Tel.:+91-120-408 5500 Ext.1540

Direct: +91-120-458 1540
Mobile : +91-9910991179

Email:r.arunkumar@isgec.co.in

website:www.isgec.com

7 Switch off as you go   |   qRecycle always   |   P Think & Print  - Save
Paper - Save Trees  |   Go Green

Please do not print this email unless it is absolutely necessary. Spread
environmental awareness.

**Comment by msrawat-isgec** [comment]
Dear Harish,

 

OK..

 

@Helpdesk Team, Please install accordingly.

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: helpdesk.noida63-request@isgec.co.in
[mailto:helpdesk.noida63-request@isgec.co.in] On Behalf Of Harish Kaushik
Sent: 03 February 2021 16:46
To: 'Praveen Kumar'
Cc: 'R. Arunkumar'; 'Esg Pragasam';
reply@reply.github.com;
vinay.sharma@isgec.co.in; dhirendra.singh@isgec.co.in; 'Support Team 63'
Subject: RE: Autocad 2020 with tool set installation request

 

Dear Praveen, 

 

No need to add AUTOCAD package separately as AEC also includes AUTOCAD.

*Adding will consume both AEC and AUTOCAD package license.

 

Thanks & Regards,

Harish Kaushik

From: Praveen Kumar <praveen1.kumar@isgec.co.in> 
Sent: 03 February 2021 15:51
To: 'Support Team 63' <helpdesk.noida63@isgec.co.in>
Cc: 'R. Arunkumar' <r.arunkumar@isgec.co.in>; 'Esg Pragasam'
<esgpragasam@isgec.co.in>; 'Harish Kaushik' <harish.kaushik@isgec.co.in>;
reply@reply.github.com;
vinay.sharma@isgec.co.in; dhirendra.singh@isgec.co.in
Subject: RE: Autocad 2020 with tool set installation request

 

 

Dear Team,

 

All mentioned applications are the part of AUTOCAD but both mentioned users
are having AEC license. Now I added Autocad license for bot users besides
AEC.

 

I download all mentioned application with required updates. Path details as
follows.

 

\\192.168.25.75\AUTODESK_2020 <file:///\\192.168.25.75\AUTODESK_2020> 

 

Please install only below mentioned applications with given updates.

*	AutoCAD Architecture -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_Architecture_2020_0_2_Update_html> 2020.0.2 (Includes
2020.0.1)
*	AutoCAD MEP -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_MEP_2020_0_2_Update_html> 2020.0.2 (Includes 2020.0.1)
*	AutoCAD Mechanical -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_Mechanical_2020_0_1_Update_html> 2020.0.1
*	AutoCAD Plant 3D -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_Plant3D_2020_1_Update_html> 2020.1 (Includes 2020.0.1)

 

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: helpdesk.noida63-request@isgec.co.in
[mailto:helpdesk.noida63-request@isgec.co.in] On Behalf Of Harish Kaushik
Sent: 29 January 2021 14:08
To: 'Praveen Kumar'; 'Support Team 63'
Cc: 'R. Arunkumar'; 'Esg Pragasam'
Subject: RE: Autocad 2020 with tool set installation request

 

Download link.

 

https://manage.autodesk.com/cep/?
<https://manage.autodesk.com/cep/?&_ga=2.113159620.1160711967.1611908667-191
4529307.1611908667#products-services/updates>
&_ga=2.113159620.1160711967.1611908667-1914529307.1611908667#products-servic
es/updates

 

From: Harish Kaushik <harish.kaushik@isgec.co.in> 
Sent: 29 January 2021 14:04
To: 'Praveen Kumar' <praveen1.kumar@isgec.co.in>; 'Support Team 63'
<helpdesk.noida63@isgec.co.in>
Cc: 'R. Arunkumar' <r.arunkumar@isgec.co.in>; 'Esg Pragasam'
<esgpragasam@isgec.co.in>
Subject: RE: Autocad 2020 with tool set installation request

 

Dear Praveen,

 

As discussed, please install following products with mentioned update
version to get benefit of Specialized Toolset of Autodesk AUTOCAD Package.

*	AutoCAD Architecture -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_Architecture_2020_0_2_Update_html> 2020.0.2 (Includes
2020.0.1)
*	AutoCAD MEP -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_MEP_2020_0_2_Update_html> 2020.0.2 (Includes 2020.0.1)
*	AutoCAD Mechanical -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_Mechanical_2020_0_1_Update_html> 2020.0.1
*	AutoCAD Electrical -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_Electrical_2020_0_1_Update_html> 2020.0.1
*	AutoCAD Plant 3D -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_Plant3D_2020_1_Update_html> 2020.1 (Includes 2020.0.1)
*	AutoCAD Map 3D -
<https://help.autodesk.com/view/ACD/2020/ENU/?guid=AutoCAD_ReleaseNotes_tool
set_updates_AutoCAD_M3D_2020_0_1_Update_html> 2020.0.1

 

 

Please ask in case of any doubt.

 

 

Thanks & Regards,

Harish Kaushik

From: R. Arunkumar <r.arunkumar@isgec.co.in> 
Sent: 29 January 2021 10:57
To: 'Praveen Kumar' <praveen1.kumar@isgec.co.in>; 'Support Team 63'
<helpdesk.noida63@isgec.co.in>
Cc: Esg Pragasam <esgpragasam@isgec.co.in>; Harish Kaushik
<harish.kaushik@isgec.co.in>
Subject: Autocad 2020 with tool set installation request

 

Dear Sir,

 

Kindly install the AutoCAD 2020 with following toolset for below person

 

Tool Set: 

 

1.	ARCHITECTURE TOOLSET
2.	MECHANICAL TOOLSET
3.	MEP TOOLSET
4.	PLANT 3D TOOLSET

 

Employee detail:

 

1.	R.Arunkumar (Emply  Code : 1974)
2.	R.Saravanan (Emply Code: 3877)

 

Regards

 
R.Arunkumar,

Boiler-Mechanical

Isgec eSign
A56,Sector-63,Noida-201301 U.P.,India

Tel.:+91-120-408 5500 Ext.1540

Direct: +91-120-458 1540
Mobile : +91-9910991179

Email:r.arunkumar@isgec.co.in

website:www.isgec.com

7 Switch off as you go   |   qRecycle always   |   P Think & Print  - Save
Paper - Save Trees  |  Description: cid:image003.jpg@01CA8223.3FC8A220 Go
Green

Please do not print this email unless it is absolutely necessary. Spread
environmental awareness.
