### ISSUE TITLE
Updation of Caesar-II 2020 version- Chennai

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-CMDB#19]
S. No | Employee Name | Employee ID | System IP address | Remarks
-- | -- | -- | -- | --
1 | S.Palaniraja | 3451 | 192.168.33.17 | Update Caesar-II 2020 version 12.00  & Licence   issue
2 | K.C.Karthick | 2555 | 192.168.33.115 | Update Caesar-II 2020 version 12.00

Request found to upgrade Caesar-II 2020 version in both above mentioned machines at Chennai Office.

@Isgec/dc-infra-team , Myself Praveen Kumar is working for the same.

**Comment by msrawat-isgec** [comment]
Dear Team,

 

Please find the path of CAESAR II 2020 version and install in both mentioned
user's machines.

 

\\192.168.25.75\design_applications
<file:///\\192.168.25.75\design_applications> 

 

 



 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: helpdesk.chennai-request@isgec.co.in
[mailto:helpdesk.chennai-request@isgec.co.in] On Behalf Of Karthick K C
Sent: 04 February 2021 14:31
To: helpdesk.chennai@isgec.co.in; praveen1.kumar@isgec.co.in
Cc: 'Palaniraja.S'
Subject: RE: Updation of Caesar-II 2020 version 

 

Dear sir

 

Kindly update the Caesar-II 2020 version 12.00  & licence issue for
following system

 


S. No

Employee Name

Employee ID

System IP address

Remarks


1

S.Palaniraja

3451

192.168.33.17

Update Caesar-II 2020 version 12.00  & Licence issue


2

K.C.Karthick

2555

192.168.33.115

Update Caesar-II 2020 version 12.00  

 

Kindly do needful

 

Regards

K.C.Karthick

 

From: Karthick K C [mailto:karthick.kc@isgec.co.in] 
Sent: 04 February 2021 12:58
To: 'helpdesk.chennai@isgec.co.in'; 'praveen1.kumar@isgec.co.in'
Cc: 'Palaniraja.S'
Subject: Updation of Caesar-II 2020 version 

 

Dear sir

 

Kindly update the Caesar-II 2020 version 12.00 in my system 

 

System IP address \\192.168.33.115 <file:///\\192.168.33.115> 

 

Regards

K.C.Karthick
