### ISSUE TITLE
Create Copy of JoolaKM for EPC

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/ITIL-CMDB#2]
Similar to the way we created a copy of JoolaKM for SMD , we have to create an instance for EPC
@bhupender-isgec - Create copy of the folder structure
@isgecharish - Understand the Menu structure for EPC

**Comment by bhupender-isgec** [comment]
Sir database joomlaepc is created on joomla (192.9.200.172)
Copied joomlasmd folder from /opt/lampp/htdocs/ & copied as joomlaepc keeping joomlasmd intact.
Modified configuration.php file in /opt/lampp/htdocs/joomlaepc/ folder & renamed database name with joomlaepc
![joomlaepc](https://user-images.githubusercontent.com/49862746/89818098-da124900-db66-11ea-8fc9-74dccf9e6cbd.jpeg)

**Comment by hariharan-isgec** [comment]
@bhupender-isgec I checked and found that the Latest SMD site is joomla3, and the database is joomla3a. Copy the into joomlaepc

**Comment by bhupender-isgec** [comment]
Ok sir

**Comment by bhupender-isgec** [comment]
Dear Sir,

 

Needfull done as per trail email . 

 

Thanks

Bhupender K Kashyap

**Comment by hariharan-isgec** [comment]
![image](https://user-images.githubusercontent.com/43699418/90424540-e99c0f80-e0db-11ea-8e32-f6728e395329.png)
@bhupender-isgec Database is not imported into joomlaepc from joomla3a, send me the steps followed to export and import the databse

**Comment by hariharan-isgec** [comment]
@bhupender-isgec I have imported the data from joomla3a to joomlaepc.
@isgecharish Please initiate configurations of Menu and other contect

**Comment by hariharan-isgec** [comment]
@isgecharish File Upload permission issue resolved. Please check

**Comment by hariharan-isgec** [comment]
@dhirendra-isgec @bhupender-isgec JoomlaEPC has bee created under JoomlaKM. Please take handover from me
