### ISSUE TITLE
[Ticket #199074] Change License Server- ETAP

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-CMDB#4]
Case is already generated in ETAP helpdesk Portal for Change ETAP License Server,
@Isgec/dc-infra-team
@praveen1.kumar@isgec.co.in
 
Thank you for using our Help Desk.

Ticket:    #199074
Subject:  Change License Server

Reply by clicking on the following link:
https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fhelpdesk.etap.com%2fcgi-bin%2fwonderdesk.cgi%3fdo%3dhd_modify_record%26help_id%3d199074%26queue%3d&c=E,1,zlUz-8dIsZStUgLbh-oR-k7JBO-u6sfEFb78pTA1TIP19ZuSM4x4coNofk7eQb1EWxBS8KYL8shP_flrXAOXS8xERRoHYIFqFVVWa-8PRNUCISFcEA,,&typo=1

We will resolve your help desk ticket as soon as possible.

ETAP Help Desk

Should you have any problems, please contact the ETAP Help Desk site administrator at HelpDesk@etap.com

**Comment by dhirendra-isgec** [comment]
I have not received mail from @Isgec/dc-infra-team

**Comment by praveen-isgec** [comment]
Hi Team,

Please do the needful as soon as possible as per mentioned ticket.

We are using ETAP Network license (through Red Dongle), Presently our server
is not working where we attached this ETAP dongle and installed license
manager. Now we want to move this dongle to another server. Please help to
do this task as soon as possible.

Current Details:
ETAP Version:	ETAP 16.1.0
Server:		Windows Server 2008 R2 Standard


If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.
Regards.....
Praveen (SYSTEMS)
 
A-8, Sector- 63, Noida, UP
Email: praveen1.kumar@isgec.co.in
website: www.isgec.com
Mobile:  +91 8448595785
	=91 9810969722


-----Original Message-----
From: ETAP Help Desk [mailto:ETAPNoReply@etap.com] 
Sent: 07 January 2021 16:34
To: Praveen Kumar
Subject: [Ticket #199074] Change License Server

Dear Praveen,

Thank you for using our Help Desk.

Ticket:    #199074
Subject:  Change License Server

Reply by clicking on the following link:
https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fhelpdesk.etap.com%2fcgi-
bin%2fwonderdesk.cgi%3fdo%3dhd_modify_record%26help_id%3d199074%26queue%3d&c
=E,1,zlUz-8dIsZStUgLbh-oR-k7JBO-u6sfEFb78pTA1TIP19ZuSM4x4coNofk7eQb1EWxBS8KY
L8shP_flrXAOXS8xERRoHYIFqFVVWa-8PRNUCISFcEA,,&typo=1

We will resolve your help desk ticket as soon as possible.

ETAP Help Desk

Should you have any problems, please contact the ETAP Help Desk site
administrator at HelpDesk@etap.com

This e-mail message is intended only for the use of the individual or entity
to which it is addressed and may contain information that is privileged,
confidential and exempt from disclosure under applicable law. If you are not
the intended recipient of this message, you are hereby notified that any
use, review, retransmission, dissemination, distribution, reproduction or
any action taken in reliance upon this message is prohibited. If you
received this message in error, please contact the sender. Any views
expressed in this message are those of the individual sender and may not
necessarily reflect the views of the company.

**Comment by dhirendra-isgec** [comment]
Please take it on priority, server health is not oaky

**Comment by praveen-isgec** [comment]
Our case is updated on ETAP portal, Now i am following for concern technical person for the same.

**Comment by praveen-isgec** [comment]
ETAP Sicense server changed sucessfull.
Old Server: 192.168.25.20 (CADISON63), Now ETAP License dongle is momed to New Server 192.168.25.55 (ANSYS6301).
Check on user's machines working fine.
@dhirendra-isgec  Please close the case.

**Comment by praveen-isgec** [comment]
Dear Sir,

As per our records, the AMC/UUC of your ETAP license serial # ISGECHEAVY expires on 1st of January, 2022.

We are attaching the proposal for the renewal of the same. Kindly go through it and let me know in case you need any clarifications.

Thanks & Regards
For ETAP Automation Pvt. Ltd.

Ankur Sood
Regional Sales Manager- North India

***@***.***
ETAP Automation Pvt Ltd
625, 6th Floor,
DLF Tower A,
Jasola, New Delhi -110025
India

Mobile: + 91 9582758591

***@***.******@***.***>

***@***.***<https://etap.com/21>

***@***.***<https://etap.com/company/news/2021/02/22/35th-anniversary-of-etap-s-passion-for-thinking-power>

===========================================
This e-mail message is intended only for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If you are not the intended recipient of this message, you are hereby notified that any use, review, retransmission, dissemination, distribution, reproduction or any action taken in reliance upon this message is prohibited. If you received this message in error, please contact the sender. Any views expressed in this message are those of the individual sender and may not necessarily reflect the views of the company.
===========================================
