### ISSUE TITLE
ISGEC- For BAAN Installation for Auditors

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-CMDB#7]
< b>Name | Contact   details
-- | --
Sanyam Chawala | 8708590939/9992767923
Akshat Jain | 9999578686
Shikhar Kumar | 8860735290

@Isgec/dc-infra-team , Myself is working for the same.

**Comment by praveen-isgec** [comment]
Needful is done for all mentioned three Auditors also given demo how to work in worktop through SSL VPN.

@dhirendra-isgec , Task complete, Please close this call.

**Comment by vinay-isgec** [comment]
Regards

Vinay

**Comment by dhirendra-isgec** [comment]
Based on Mr. KC approval, SSL VPN given to Audit users and demonstrated
